### ISSUE TITLE
Get Datasets

### ISSUE THREAD

**Issue by Jisoo-Min** [jiisoo/NLP-FindLoop#1]
Try to gather datasets upto 1,000

**Comment by Jisoo-Min** [comment]
there are several web sites to cite

1. https://www.w3resource.com/python-exercises/basic/
2. https://www.geeksforgeeks.org/python-programming-examples/
3. https://beginnersbook.com/2018/02/python-programs/
4. https://www.programiz.com/python-programming/examples
5. https://codingbat.com/python

**Comment by jinwook1240** [comment]
completed codingbat crawling,
now we need mark if built-in function using loop

**Comment by jinwook1240** [comment]
Reopened this issue to make other sites to be crawled.  
commits about crawling will refer this issue.
